---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ target_aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ target_aws_secret_access_key }}"
    AWS_REGION: "{{ target_aws_region }}"
  tasks: []
