---
- name: "Get configuration of Lambda function on AWS : {{ source_name }}"
  lambda_facts:
    query: config
    function_name: "{{ source_name }}"
  register: function_configuration
- name: "Extend role of Lambda function on AWS : {{ source_name }}"
  vars:
    function_role: "{{ function_configuration.ansible_facts.lambda_facts.function[source_name].role }}"
    function_role_name: "{{ function_role.split(':')[5].split('/')[1] }}"
    assume_role_policy_document: assume_role_policy_document.json.j2
  iam_role:
    name: "{{ function_role_name }}"
    assume_role_policy_document: "{{ lookup('template', assume_role_policy_document) }}"
    managed_policy:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
    purge_policies: no
